version: '3.8'

services:
  app-base:
    image: "${PROJECT_NAME:-your_core_library}:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}

  app:
    extends:
      service: app-base

  app-dev:
    extends:
      service: app-base
    profiles:
      - "dev"
    command: ["uvicorn", "web_example.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./examples/web:/app/web_example
      - ./src:/app/src

# Example of a database service (if you need one)
#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env.db # Separate .env for database credentials
#    ports:
#      - "5432:5432"

# volumes: # Define persistent volumes if needed
#  postgres_data:
